import type { Draft } from '../../context/InvestmentPlannerContext';

export const PRESET_TEMPLATES: Draft[] = [
  {
    name: '🏔️ Austrian 14-Salary Optimizer',
    timestamp: 1700000000000,
    country: 'AT',
    salaryPeriod: 'monthly',
    grossMonthly: 4200,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 1600,
    startCapital: 10000,
    monthlyInvest: 800,
    juneExtra: 2200,
    decemberExtra: 2200,
    years: 25,
    minRate: 6.0,
    maxRate: 10.0,
    stepUpRate: 2.0,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: false,
    inflationRate: 2.0,
    taxShieldMode: false,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [],
    extraInvestments: [],
  },
  {
    name: '🛡️ Conservative / Balanced FIRE',
    timestamp: 1700000000001,
    country: 'AT',
    salaryPeriod: 'monthly',
    grossMonthly: 3800,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 1500,
    startCapital: 25000,
    monthlyInvest: 650,
    juneExtra: 1500,
    decemberExtra: 1500,
    years: 20,
    minRate: 4.5,
    maxRate: 7.0,
    stepUpRate: 1.5,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: true,
    inflationRate: 2.5,
    taxShieldMode: false,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [],
    extraInvestments: [],
  },
  {
    name: '🚀 Aggressive Global Equity DCA',
    timestamp: 1700000000002,
    country: 'AT',
    salaryPeriod: 'monthly',
    grossMonthly: 5500,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 1800,
    startCapital: 15000,
    monthlyInvest: 1400,
    juneExtra: 3000,
    decemberExtra: 3000,
    years: 30,
    minRate: 7.0,
    maxRate: 11.0,
    stepUpRate: 3.0,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: false,
    inflationRate: 2.0,
    taxShieldMode: false,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [],
    extraInvestments: [],
  },
  {
    name: '🏰 Hungarian TBSZ 0% Tax Shelter',
    timestamp: 1700000000003,
    country: 'HU',
    salaryPeriod: 'monthly',
    grossMonthly: 3000,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 900,
    startCapital: 8000,
    monthlyInvest: 600,
    juneExtra: 0,
    decemberExtra: 0,
    years: 20,
    minRate: 7.0,
    maxRate: 10.0,
    stepUpRate: 2.0,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: false,
    inflationRate: 3.0,
    taxShieldMode: true,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [],
    extraInvestments: [],
  },
  {
    name: '🏝️ Coast FIRE Jumpstart',
    timestamp: 1700000000004,
    country: 'AT',
    salaryPeriod: 'monthly',
    grossMonthly: 3500,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 1400,
    startCapital: 60000,
    monthlyInvest: 300,
    juneExtra: 500,
    decemberExtra: 500,
    years: 25,
    minRate: 6.5,
    maxRate: 9.5,
    stepUpRate: 0,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: true,
    inflationRate: 2.0,
    taxShieldMode: false,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [],
    extraInvestments: [],
  },
  {
    name: '🏡 Family & Property Milestone Plan',
    timestamp: 1700000000005,
    country: 'AT',
    salaryPeriod: 'monthly',
    grossMonthly: 4800,
    zuschlagMonthly: 0,
    zuschlagSvsSubject: true,
    fixedCosts: 1700,
    startCapital: 20000,
    monthlyInvest: 900,
    juneExtra: 2000,
    decemberExtra: 2000,
    years: 25,
    minRate: 6.0,
    maxRate: 9.0,
    stepUpRate: 2.0,
    lifeInsurance: 0,
    loanRepayment: 0,
    adjustForInflation: false,
    inflationRate: 2.0,
    taxShieldMode: false,
    expenseMode: 'simple',
    expenseItems: [],
    milestones: [
      { id: 'm1', name: 'Real Estate Downpayment', amount: 300, type: 'decrease', startYear: 7, reinvest: false },
      { id: 'm2', name: 'Child Education Bonus', amount: 200, type: 'increase', startYear: 18, reinvest: false }
    ],
    extraInvestments: [
      { id: 'e1', name: 'Property Downpayment Lump Sum', amount: 60000, year: 7, applyUpcomingYears: false }
    ],
  }
];
